[package]
name = "game_case_creator"
version = "0.1.0"
edition = "2024"

[dependencies]
confy = "1.0.0"
cursive = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
shellexpand = "3.1.1"
thiserror = "2.0.12"
