[package]
name = "game_case_parser"
version = "0.1.0"
edition = "2024"

[lib]
name = "game_case_parser"
crate-type = ["rlib", "staticlib"]

[dependencies]
ebml-iterable = { version = "0.6.3", features = ["derive-spec"] }